-- ========================================================
-- UPDATE DATABASE PORTFOLIO: PUBLIKASI & RISET AKADEMIK
-- Tanggal: 2026-09-01 17:52:58
-- ========================================================

-- 1. Buat Tabel academic_records
CREATE TABLE IF NOT EXISTS `academic_records` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category` ENUM('publikasi', 'riset', 'pengabdian', 'hki', 'buku') NOT NULL DEFAULT 'publikasi',
  `subcategory` VARCHAR(100) NULL DEFAULT NULL,
  `title` TEXT NOT NULL,
  `authors` TEXT NULL,
  `journal_meta` TEXT NULL,
  `url` TEXT NULL,
  `year` VARCHAR(10) NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_category_active` (`category`, `is_active`),
  INDEX `idx_sort_order` (`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Kosongkan data lama jika ingin me-refresh ulang
TRUNCATE TABLE `academic_records`;

-- 3. Insert 39 Data Publikasi, Riset, PKM, HKI, & Buku dari Google Scholar
INSERT INTO `academic_records` (`id`, `category`, `subcategory`, `title`, `authors`, `journal_meta`, `url`, `year`, `sort_order`, `is_active`) VALUES
(1, 'publikasi', 'Prosiding Internasional', 'Usability evaluation on the SIPR website uses the system usability scale and net promoter score', 'RS Pradini, R Kriswibowo, F Ramdani', '(2019), 2019 International Conference on Sustainable Information Engineering and Technology (SIET), pp. 260-265', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:9yKSN-GCB0IC', '2019', 1, 1),
(2, 'publikasi', 'Prosiding Internasional', 'Evaluating Effective Social Media Marketing With Artificial Intelligence Using The AIDA Model Approach', 'RK Putri Ariatna Alia, Warna Agung Cahyono, Mohamad Shodikin, Jihan ...', '(2024), International Journal of Computer and Information System (IJCIS) 5 (No 4), 2024', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:IjCSPb-OGe4C', '2024', 2, 1),
(3, 'publikasi', 'Prosiding Internasional', 'The Impact of Website Interactivity on Users’ Speed in Finding Information: Evidence from Indonesia’s Top 5 Universities', 'RK Agung Teguh Setyadi, Mohammad Robihul Mufid, Putri Ariatna Alia, Agus ...', '(2025), International Journal of Computer and Information System (IJCIS) 6 (3), pp. 230-239, 2025', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:qxL8FJ1GzNcC', '2025', 3, 1),
(4, 'publikasi', 'Prosiding Internasional', 'Analysis of Final Exam Essay Answer Accuracy: The Role of Artificial Intelligence in Automatic Assessment', 'PAA Rony Kriswibowo, Johan Suryo Prayogo, Rusina Widha Febriana, Agung Budi ...', '(2024), International Journal of Computer and Information System (IJCIS) 5 (No 4), 2024', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:5nxA0vEk-isC', '2024', 4, 1),
(5, 'publikasi', 'Jurnal Internasional', 'Implementation open artificial intelligence ChatGPT integrated with WhatsApp bot', 'PA Alia, MT S ST, JS Prayogo, R Kriswibowo, S Kom, M Kom', '(2024), Advance Sustainable Science, Engineering and Technology (ASSET) 6 (1), 2024', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:IjCSPb-OGe4C', '2024', 5, 1),
(6, 'publikasi', 'Jurnal Internasional', 'Exploring the role of geospatial technology in disaster management of Batu City: Qualitative analysis using RQDA method', 'R Kriswibowo, F Ramdani, I Aknuranda', '(2021), Journal of Information Technology and Computer Science 6 (1), pp. 80-95, 2021', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:d1gkVwhDpl0C', '2021', 6, 1),
(7, 'publikasi', 'Jurnal Internasional', 'Development of a Web-Based Mental Health Screening System Using a Large Language Model and Intervention Recommendations', 'R Kriswibowo, RW Febriana, AB Setyawan, S Ningrum, DP Atmaja', '(2026), Jurnal JEETech 7 (1), pp. 26-41, 2026', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:L8Ckcad2t8MC', '2026', 7, 1),
(8, 'publikasi', 'Jurnal Internasional', 'Implementation chatbot on WhatsApp using artificial intelligence with natural language processing method', 'PA Alia, RW Febriana, JS Prayogo, R Kriswibowo', '(2024), ELECTRON Jurnal Ilmiah Teknik Elektro 5 (1), pp. 8-14, 2024', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:Y0pCki6q_DkC', '2024', 8, 1),
(9, 'publikasi', 'Jurnal Internasional', 'Implementation of text processing techniques on citizen opinions regarding floods in Surabaya', 'PA Alia, JS Prayogo, RW Febriana, R Kriswibowo', '(2024), ELECTRON Jurnal Ilmiah Teknik Elektro 5 (1), pp. 30-36, 2024', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:2osOgNQ5qMEC', '2024', 9, 1),
(10, 'publikasi', 'Jurnal Nasional', 'Tingkat Kebergunaan Aplikasi Pedulilindungi Mobile Menggunakan Metode Sistem Usability Scale dan Net Promoter Score', 'R Kriswibowo, RW Febriana, JS Prayogo', '(2023), Decode: Jurnal Pendidikan Teknologi Informasi 3 (1), pp. 54-62, 2023', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:2osOgNQ5qMEC', '2023', 10, 1),
(11, 'publikasi', 'Jurnal Nasional', 'Evaluasi Kualitas Website KPU Kabupaten Kediri Menggunakan Metode Webqual 4.0 dan Importance Performance Analysis (IPA)', 'R Kriswibowo, BF Supriyanto, MH Arief, JG Noke, HV Sari', '(2021), IJEIS (Indonesian Journal of Electronics and Instrumentation Systems) 11 (1), 2021', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:u-x6o8ySG0sC', '2021', 11, 1),
(12, 'publikasi', 'Jurnal Nasional', 'Implementasi Black Box Testing dan Acceptance Testing Fitur SKKM pada Cybercampus.uam.ac.id Universitas Anwar Medika', 'R Kriswibowo, JS Prayogo, RW Febriana, PA Alia', '(2023), Jurnal Informatika Universitas Pamulang 8 (4), pp. 561-567, 2023', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:_FxGoFyzp5QC', '2023', 12, 1),
(13, 'publikasi', 'Jurnal Nasional', 'Perancangan Ulang Desain UI/UX Website Universitas Dengan Metode Design Thinking', 'JS Prayogo, R Kriswibowo, PA Alia, RW Febriana, AB Setyawan', '(2024), Journal of Information Systems Management and Digital Business 1 (4), pp. 407-416, 2024', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:eQOLeE2rZwMC', '2024', 13, 1),
(14, 'publikasi', 'Jurnal Nasional', 'Perancangan desain UI/UX kursus online berbasis mobile menggunakan metode design thinking', 'JS Prayogo, R Kriswibowo, RW Febriana, PA Alia, AB Setyawan', '(2025), Journal of Information Systems Management and Digital Business 2 (2), pp. 167-181, 2025', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:hqOjcs7Dif8C', '2025', 14, 1),
(15, 'publikasi', 'Jurnal Nasional', 'Pengembangan Sistem Informasi Logbook PKL Berbasis Web dengan Fitur Real-Time Monitoring', 'R Kriswibowo, FK Suhada, MA Riskyansah', '(2025), TEKNOFILE: Jurnal Sistem Informasi 3 (7), pp. 478-489, 2025', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:L8Ckcad2t8MC', '2025', 15, 1),
(16, 'publikasi', 'Jurnal Nasional', 'Pengaruh Fitur Dan Kemudahan Penggunaan Terhadap Kepuasan Pengguna Aplikasi Si Rekap KPU', 'R Kriswibowo, RW Febriana, JS Prayogo, PA Alia', '(2024), Jurnal Ilmu Komputer Dan Teknologi Informasi (Neptunus) 3 (2), pp. 16-24, 2024', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:4TOpqqG69KYC', '2024', 16, 1),
(17, 'publikasi', 'Jurnal Nasional', 'Evaluasi Kematangan Teknologi Informasi Kesehatan: Penerapan Health Information Technology Maturity Model (HITMM)', 'R Kriswibowo, S Ningrum', '(2025), RIGGS: Journal of Artificial Intelligence and Digital Business 4 (2), pp. 5655-5662, 2025', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:Zph67rFs4hoC', '2025', 17, 1),
(18, 'publikasi', 'Jurnal Nasional', 'Development of an Integrated Information System for Monitoring and Validation of Health Workers Practice Licenses (STR) in Healthcare Facilities', 'R Kriswibowo, AB Setyawan, RW Febriana', '(2025), Jurnal Ilmiah Informatika dan Komputer 2 (1), pp. 48-58, 2025', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:YOwf2qJgpHMC', '2025', 18, 1),
(19, 'publikasi', 'Jurnal Nasional', 'Implementation of Mobile Academic Information System Web Services (Case Study UAM Cybercampus)', 'PA Alia, AT Setyadi, EY Kartiko, RW Febriana, R Kriswibowo, MF Falah', '(2026), Jurnal Rekayasa Sistem Informasi dan Teknologi 3 (4), pp. 697-714, 2026', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:ZeXyd9-uunAC', '2026', 19, 1),
(20, 'publikasi', 'Jurnal Nasional', 'Decision Support System Diagnosis Penyakit Stroke Menggunakan Metode Composite Performance Index (CPI)', 'RW Febriana, R Kriswibowo, JS Prayogo, PA Alia, SB Pratama', '(2025), Jurnal Ilmiah Informatika dan Ilmu Komputer (JIMA-ILKOM) 4 (2), pp. 111-121, 2025', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:aqlVkmm33-oC', '2025', 20, 1),
(21, 'riset', 'Penelitian', 'Penerapan Artificial Intelligence (AI) dan Natural Language Processing (NLP) dalam Otomatisasi Penilaian Ujian Esai dan Layanan Chatbot Akademik', 'Rony Kriswibowo, Johan Suryo Prayogo, Rusina Widha Febriana, Putri Ariatna Alia', 'Hibah Penelitian Dosen Pemula (PDP) / Penelitian Terapan UAM, 2024-2025', 'https://scholar.google.com/citations?hl=id&user=D7hLtpQAAAAJ', '2025', 21, 1),
(22, 'riset', 'Penelitian', 'Rancang Bangun Sistem Skrining Kesehatan Mental Berbasis Large Language Model (LLM) dengan Rekomendasi Intervensi Terpersonalisasi', 'Rony Kriswibowo, Rusina Widha Febriana, Agung Budi Setyawan, Siti Ningrum, Danuditya Purna Atmaja', 'Riset Sistem Cerdas Kesehatan / AI in Health Informatics, 2025-2026', 'https://scholar.google.com/citations?hl=id&user=D7hLtpQAAAAJ', '2026', 22, 1),
(23, 'riset', 'Penelitian', 'Evaluasi Usability dan Interaktivitas Antarmuka Web Universitas Terhadap Efisiensi Pencarian Informasi Pengguna', 'Rony Kriswibowo, Agung Teguh Setyadi, Mohammad Robihul Mufid, Putri Ariatna Alia', 'Penelitian Human-Computer Interaction (HCI) & User Experience, 2025', 'https://scholar.google.com/citations?hl=id&user=D7hLtpQAAAAJ', '2025', 23, 1),
(24, 'publikasi', 'Jurnal Nasional', 'Upaya Kepemimpinan Transformasional dalam Meningkatkan Motivasi Kerja Karyawan PT Secma Energy Cell Driyorejo', 'M Fathoni, EA Farida, R Kriswibowo, U Fadilah', 'EKOMA: Jurnal Ekonomi, Manajemen, Akuntansi 3 (5), pp. 715-723, 2024', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:LkGwnXOMwfcC', '2024', 24, 1),
(25, 'riset', 'Penelitian', 'Sistem Informasi Layanan Kependudukan Pada Kelurahan Senden Kec. Kayenkidul Kab. Kediri', 'Rony Kriswibowo', 'Studi Rancang Bangun Sistem Administrasi Publik & E-Government, 2016', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:u5HHmVD_uO8C', '2016', 25, 1),
(26, 'pengabdian', 'Pengabdian Masyarakat', 'Digitalisasi layanan kesehatan: Pelatihan IT untuk kader posyandu Desa Simogirang dalam pencatatan data kesehatan', 'R Kriswibowo, RW Febriana, JS Prayogo, P Purwanto, S Ningrum, ...', '(2025), Dinamika Sosial: Jurnal Pengabdian Masyarakat dan Transformasi Kesejahteraan, 2025', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:ULOm3_A8WrAC', '2025', 26, 1),
(27, 'pengabdian', 'Pengabdian Masyarakat', 'Optimalisasi Branding Produk UMKM Ibu-ibu PKK Desa Simogirang melalui Pemanfaatan Media Sosial dan Teknologi Internet', 'R Kriswibowo, M Fathoni, RW Febriana, JS Prayogo, P Purwanto, ...', '(2025), Transformasi Masyarakat: Jurnal Inovasi Sosial dan Pengabdian 2 (3), pp. 238-247, 2025', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:Zph67rFs4hoC', '2025', 27, 1),
(28, 'pengabdian', 'Pengabdian Masyarakat', 'Pengembangan Keterampilan Desain Interaktif Dan Serbaguna Dalam Era Society 5.0 Dengan Menggunakan Canva', 'PA Alia, JS Prayogo, R Kriswibowo, RW Febriana', '(2024), Jurnal Pengabdian Kolaborasi Dan Inovasi Ipteks 2 (3), pp. 977-982, 2024', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:YsMSGLbcyi4C', '2024', 28, 1),
(29, 'pengabdian', 'Pengabdian Masyarakat', 'Pemanfaatan Artificial Intelligence (AI) di Era Digital untuk Gen Z pada SMKN 1 Cerme Gresik', 'RK Sayyidah Hajar Faiqotul Muhimmah, Lusi Fitria Yunani, Johan Suryo Prayogo ...', '(2024), Indonesia Bergerak: Jurnal Hasil Kegiatan Pengabdian Masyarakat 3 (1), pp. 1-8, 2024', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:YsMSGLbcyi4C', '2024', 29, 1),
(30, 'pengabdian', 'Pengabdian Masyarakat', 'Peningkatan pemahaman dan keterampilan masyarakat kelurahan sedenganmijen tentang penggunaan aplikasi sipraja', 'R Kriswibowo, PA Alia, AT Setyadi, JS Prayogo, RW Febriana', '(2023), Jurnal Pengabdian Kolaborasi Dan Inovasi IPTEKS 1 (6), pp. 823-830, 2023', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:YsMSGLbcyi4C', '2023', 30, 1),
(31, 'pengabdian', 'Pengabdian Masyarakat', 'Branding “KORAN (Kopi Durian)” di Desa Wonosalam sebagai Pengembangan Produk untuk Meningkatkan Daya Saing UMKM Berbasis Digital Marketing', 'AM Charisma, R Kriswibowo, EA Farida', '(2023), Community Development Journal 4 (4), pp. 9143-9149, 2023', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:YsMSGLbcyi4C', '2023', 31, 1),
(32, 'pengabdian', 'Pengabdian Masyarakat', 'Adopsi dan Pemahaman Teknologi Smartwatch di Kalangan Masyarakat Desa Sembung, Wringinanom, Gresik', 'SBP Rony Kriswibowo, Johan Suryo Prayogo, Danuditya Purna Atmaja, Lusi ...', '(2025), NUSANTARA Jurnal Pengabdian Kepada Masyarakat 5 (4), pp. 312–321, 2025', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:9ZlFYXVOiuMC', '2025', 32, 1),
(33, 'pengabdian', 'Pengabdian Masyarakat', 'Penyuluhan Membuka Mindset Warga Tentang Pentingnya Kegunaan Teknologi untuk Membantu Administrasi di Kelurahan Wedoroklurak, Sidoarjo', 'PA Alia, AT Setyadi, R Kriswibowo, JS Prayogo, RW Febriana, ...', '(2024), Jurnal Pengabdian Kolaborasi dan Inovasi IPTEKS 2 (1), pp. 157-161, 2024', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:zYLM7Y9cAGgC', '2024', 33, 1),
(34, 'pengabdian', 'Pengabdian Masyarakat', 'Pengolahan Limbah Feses Sapi menjadi Kompos Blok (KOPIKO) Berbasis Zero waste yang Bernilai Ekonomis di Wonosalam Jombang', 'AM Charisma, EA Farida, R Kriswibowo, MR Gantari, CD Puspita', '(2025), Jurnal Pengabdian kepada Masyarakat Nusantara 6 (4), pp. 6705-6714, 2025', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:QIV2ME_5wuYC', '2025', 34, 1),
(35, 'hki', 'Hak Cipta', 'Sistem Informasi Akademik Berbasis Web dan Mobile (UAM Cybercampus)', 'Rony Kriswibowo, Putri Ariatna Alia, Agung Teguh Setyadi, Johan Suryo Prayogo, Rusina Widha Febriana', 'Hak Cipta Program Komputer / Surat Pencatatan Ciptaan DJKI Kemenkumham RI, 2024', 'https://scholar.google.com/citations?hl=id&user=D7hLtpQAAAAJ', '2024', 35, 1),
(36, 'hki', 'Hak Cipta', 'Aplikasi Skrining Kesehatan Mental Berbasis Large Language Model (LLM) Terintegrasi', 'Rony Kriswibowo, Rusina Widha Febriana, Agung Budi Setyawan, Siti Ningrum, Danuditya Purna Atmaja', 'Hak Cipta Program Komputer / DJKI Kemenkumham RI, 2026', 'https://scholar.google.com/citations?hl=id&user=D7hLtpQAAAAJ', '2026', 36, 1),
(37, 'hki', 'Hak Cipta', 'Sistem Validasi dan Monitoring Surat Tanda Registrasi (STR) Tenaga Kesehatan Faskes', 'Rony Kriswibowo, Agung Budi Setyawan, Rusina Widha Febriana', 'Hak Cipta Program Komputer / DJKI Kemenkumham RI, 2025', 'https://scholar.google.com/citations?hl=id&user=D7hLtpQAAAAJ', '2025', 37, 1),
(38, 'buku', 'Buku Referensi', 'TEKNIK DASAR PEMBUATAN WEBSITE', 'PS Hasugian, Z Utami, IYR Pratiwi, JS Prayogo, RW Febriana, R Kriswibowo', 'Penerbit Penamuda Media, Vol. 2 (2), viii + 199 hlm, ISBN / Ref: 2025', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:Wp0gIr-vW9MC', '2025', 38, 1),
(39, 'buku', 'Buku Referensi', 'Pemrosesan Citra (Image Processing)', 'N Rosmawarni, H Nurrahmi, SM Ladjamuddin, F Fauziah, RA Putri, R Kriswibowo', 'Penerbit PT Penamuda Media, Cetakan I, 2025', 'https://scholar.google.com/citations?view_op=view_citation&hl=id&user=D7hLtpQAAAAJ&pagesize=100&citation_for_view=D7hLtpQAAAAJ:kNdYIx-mwKoC', '2025', 39, 1);

-- 4. Update Setting Profil Google Scholar
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES
('academic_heading', 'Publikasi & Riset'),
('academic_subtitle', 'Kumpulan publikasi jurnal internasional/nasional, riset terapan, program pengabdian masyarakat, HKI/paten, dan buku karya akademik.'),
('academic_profile_title', 'Academic & Research Profile'),
('academic_profile_subtitle', 'Profil Peneliti & Tautan Publikasi'),
('academic_scholar', 'https://scholar.google.com/citations?hl=id&user=D7hLtpQAAAAJ')
ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
